maze_n: [3, 3]
maze_scaling: 10
maze_i: [0, 0]

cell_size: 1
RADIUS: 3

movement_stepsize: 1
delta_t: 1

#alpha: [0.0001, 0.0001, 0.01, 0.0001, 0.0001, 0.0001]
alpha: [0,0,0,0,0,0]

initial_occupancy_map_size: [150, 150]
cushion: 50 #must be greater than the maximum range of the sensor
resize_magnitude: 200
initial_weight: .5

rmax: 30
beam_width: 15
sensor_penetration: 5
dr: 0.3
dtheta: 0.017453292519943295 #(2*pi/360) every degree
num_sensors: 6
num_particle: 20

zmax: .3
zhit: .6
zrandom: .1
#sigma_hit: .04
sigma_hit: 0

# l_occ = np.log(0.65/0.35)
#l_occ: 0.2688453123
# l_free = np.log(0.35/0.65)
#l_free: -0.2688453123
# lo = np.log(0.4/0.6)
#l_o: -0.1760912591

l_occ: 20
l_free: 0.6
l_o: 0.2
